apiVersion: batch/v1
kind: Job
metadata:
 name: pytorch-job
spec:
 completions: 1
 parallelism: 1
 template:
  spec:
   restartPolicy: Never
   containers:
   - name: pytorch-con
     image: git.ecdf.ed.ac.uk/hsamuel/multi-node_pytorch
     imagePullPolicy: Always
     command: ["python3"]
     args: ["main.py"]
     resources:
      requests:
       cpu: 1
       memory: "4Gi"
      limits:
       cpu: 1
       memory: "8Gi"
       nvidia.com/gpu: 1
