apiVersion: v1
kind: Pod
metadata:
 name: lightweight-pod
spec:
 containers:
 - name: data-loader
   image: dimmestp/multi_node_pytorch:latest
   command: ["sleep", "infinity"]
   resources:
    requests:
     cpu: 1
     memory: "1Gi"
    limits:
     cpu: 1
     memory: "1Gi"
     nvidia.com/gpu: 1
   volumeMounts:
   - mountPath: /mnt/ceph_rbd
     name: volume
   - mountPath: /code
     name: github-code
 initContainers:
 - name: lightweight-git-container
   image: cicirello/alpine-plus-plus
   command: ['sh', '-c', "cd /code; git clone https://github.com/DimmestP/multi_node_pytorch.git"]
   resources:
    requests:
     cpu: 1
     memory: "1Gi"
    limits:
     cpu: 1
     memory: "1Gi"
   volumeMounts:
   - mountPath: /code 
     name: github-code
 volumes:
 - name: volume
   persistentVolumeClaim:
    claimName: benchmark-imagenet-pvc
 - name: github-code
   emptyDir:
    sizeLimit: 1Gi
