apiVersion: batch/v1
kind: Job
metadata:
 name: pytorch-job
spec:
 completions: 1
 parallelism: 1
 template:
  spec:
   restartPolicy: Never
   containers:
   - name: pytorch-con
     image: dimmestp/multi_node_pytorch:latest
     command: ["python3"]
     args: ["main.py"]
     resources:
      requests:
       cpu: 10
       memory: "40Gi"
      limits:
       cpu: 10
       memory: "80Gi"
       nvidia.com/gpu: 1
     volumeMounts:
     - mountPath: /mnt/ceph_rbd
       name: volume
   volumes:
   - name: volume
     persistentVolumeClaim:
      claimName: benchmark-imagenet-pvc
