apiVersion: batch/v1
kind: Job
metadata:
 name: pytorch-job
spec:
 completions: 1
 parallelism: 1
 template:
  spec:
   restartPolicy: Never
   containers:
   - name: pytorch-con
     image: dimmestp/multi_node_pytorch:latest
     command: ["python3"]
     args: ["multi_node_pytorch/code/main.py"]
     resources:
      requests:
       cpu: 10
       memory: "40Gi"
      limits:
       cpu: 10
       memory: "80Gi"
       nvidia.com/gpu: 1
     volumeMounts:
     - mountPath: /mnt/ceph_rbd
       name: volume
     - mountPath: /code
       name: github-code
   initContainers:
   - name: lightweight-git-container
     image: cicirello/alpine-plus-plus
     command: ['sh', '-c', "cd /code; git clone https://github.com/DimmestP/multi_node_pytorch.git"]
     resources:
      requests:
       cpu: 1
       memory: "4Gi"
      limits:
       cpu: 1
       memory: "8Gi"
     volumeMounts:
     - mountPath: /code 
       name: github-code
   volumes:
   - name: volume
     persistentVolumeClaim:
      claimName: benchmark-imagenet-pvc
   - name: github-code
     emptyDir:
      sizeLimit: 1Gi
